version: '3.6'

services:
  web:
    restart: always
    build: ./web
    expose:
      - 8000
    volumes:
      - ./web:/usr/src/app
    env_file:
      - web/.env
    depends_on:
      - postgres

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
#    volumes:
#      - /www/static
    depends_on:
      - web

  postgres:
    restart: always
    build: ./postgresql
    env_file:
      - postgresql/.env
    ports:
      - 5432:5432