"""empty message

Revision ID: 267df11280d1
Revises: f278916fb9f0
Create Date: 2018-10-04 16:49:46.890114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267df11280d1'
down_revision = 'f278916fb9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_name', table_name='user')
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.create_index('ix_user_name', 'user', ['name'], unique=1)
    # ### end Alembic commands ###
